#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
cd icis/icis-ui
# eslint --fix ./src --ext .vue,.js
# STAGE_FILES="$(git diff --cached --name-only --diff-filter=ACM -- '*.vue' '*.js')"
# echo ${#STAGE_FILES}
# if test 0 -gt 0
npx lint-staged
# then
# echo 2
